name: "React_CD Pipline"

on:
    workflow_run:
        workflows: ["React CI/CD pipline/workflow"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: "Setup node js"
              uses: actions/setup-node@v4
              with:
                node-version: '21'

            - name: "Setup vercal cil"
              run: npm install -g vercel


            - name: "Download the build artifact"
              uses: actions/download-artifact@v4
              with:
                    name: build
                    run-id: ${{ github.event.workflow_run.id }}
                    github-token: ${{ github.token }}

            - name: "Deploy to Vercel"
              run: vercel --prod --token=${{  secrets.VERCAL_TOKEN  }} --confirm --name=react-cd-pipeline 
              